### ISSUE TITLE
ReferenceError: proximiio is not defined

### ISSUE THREAD

**Issue by nileshlg2003** [proximiio/proximiio-ionic-demo#1]
I downloaded this example,  updated my app keys and AuthTOken in service.js. and run the npm install in ionic cli, But when I run the app, I get this error,

```
ReferenceError: proximiio is not defined
    at Object.init (http://localhost:8100/js/services.js:6:7)
    at http://localhost:8100/js/controllers.js:40:15
    at Object.ionic.Platform.ready (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2122:9)
    at new <anonymous> (http://localhost:8100/js/controllers.js:12:18)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13277:17)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13285:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17841:28
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52255:24)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50449:41)
    at Object.switcher.init (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50369:20) <ion-nav-view name="tab-dash" class="view-container tab-content" nav-view="active" nav-view-transition="android">
```

**Comment by MikaKoskiola** [comment]
Based on the logs it seems you're trying to run the app inside a simulator. You need to use "ionic run android --device" or "ionic run ios --device" to run the application on a real device instead of the simulator. This fact might not be too obvious in the readme file but we've emphasized that at the Ionic Market.

**Comment by nileshlg2003** [comment]
yes, I was running it on web using ionic serve, but then I run it on Android device and the app built properly and run. But Nothing happes in Proximity Status, I mean, Input Type and Input Object fields are set to "Discovering.." and outputs in null, Position field does show correctly. I followed the Proximiio demo video to create places and all the steps, also the app ID and token is correct, But I am not receiving any push notifications.

**Comment by MikaKoskiola** [comment]
We tried the Ionic starter few times our self and everything seems to work ok. We also haven't received any reports to Fabrics crashalytics so it's hard to say what's causing this. In case you're still experiencing these issues, can you send the application id and auth-token to support@proximi.io so we can try the starter with your credentials?

**Comment by nileshlg2003** [comment]
thanks for replying. I also tried the Proximiio Android Demo (Native). same case I don't get the push notification even after setting up the Google console api etc. I have GCM enabled there. 
Anyways I am sending the APP ID and token via email now.

**Comment by MikaKoskiola** [comment]
I'm closing this issue per discussion we had via Skype earlier. We've tried all the possible combinations regarding geofencing with Android and we couldn't replicate this issue (worked OK even with your tokens). We also didn't find any errors during our remote debugging session which makes it hard to pinpoint the cause for this issue. We're working towards SDK update for both Android and iOS; feel free to try the updated SDK after it's released and re-open this issue in case the problem still exists.

**Comment by nileshlg2003** [comment]
Hi Mika,

Hope you are doing well.
I was wondering if you could help me with some of the queries about
proximi.io

In my application, I have some users who will have their own preferences to
select categories for which they want to get push notification on
geofences. How can I achieve it?
I need to show all the filtered, geofences related to user's selected
categories on map (different color pin for each category) Is there any
proper documentation about How can I retrieve all the places/ geofences
from my account? Is there any support for categories? How can I save the
push notifications to my own database? are these features available in free
tier or do I have to upgrade?

apologies in advance if my writing confused you. Its easier to explain in
person than to write :(

regards,
Nilesh

**Comment by MikaKoskiola** [comment]
Hi,

I'll get back to you on this matter as soon as we can come up with an idea on how to achieve on this using Proximi.io.
